# Setup
title:            Hyde
tagline:          'test tagline'
description:      'test description'
url:              https://github.com/Keller-Michael/a-mind-forever-voyaging
baseurl:          https://github.com/Keller-Michael/a-mind-forever-voyaging/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Keller-Michael/a-mind-forever-voyaging
